// LMS 샘플 데이터
export const lmsSampleData = {
  "course": {
    "id": 31,
    "code": "JSON_COURSE_17497",
    "title": "요즘 일잘러가 쓰는 BEST 생성형 AI",
    "summary": "labs 맟춤형 HLAC09001",
    "estimated_hours": "2.00",
    "difficulty": "BEGINNER",
    "language": "ko"
  },
  "learning_index": [
    {
      "learner_id": 1,
      "course_id": 31,
      "index_id": 785,
      "index_type": "CHAPTER",
      "is_required": 1,
      "pass_score": null,
      "pass_progress_ratio": null,
      "pass_required_count": null,
      "assessment_score": null,
      "assessment_progress_ratio": null,
      "assessment_count": null,
      "index_order": 1,
      "learning_status": "PENDING",
      "parent_index_id": null,
      "index_title": "학습",
      "learning_period_start_at": "2025-01-01T00:00:00Z",
      "learning_period_end_at": "2025-12-31T23:59:59Z",
      "learning_time": 0,
      "progress_ratio_target_type": null,
      "pass_process_timing_type": null,
      "review_period_end_at": "2026-01-31T23:59:59Z",
      "is_assessment": 0,
      "assessment_title": null,
      "assessment_ratio": null,
      "learning_content": [],
      "learning_index": [
        {
          "learner_id": 1,
          "course_id": 31,
          "index_id": 787,
          "index_type": "CHAPTER",
          "is_required": 1,
          "pass_score": null,
          "pass_progress_ratio": null,
          "pass_required_count": null,
          "assessment_score": null,
          "assessment_progress_ratio": null,
          "assessment_count": null,
          "index_order": 1,
          "learning_status": "PENDING",
          "parent_index_id": 785,
          "index_title": "AI 모델의 진화와 생성형 AI 이해하기",
          "learning_period_start_at": "2025-01-01T00:00:00Z",
          "learning_period_end_at": "2025-12-31T23:59:59Z",
          "learning_time": 0,
          "progress_ratio_target_type": null,
          "pass_process_timing_type": null,
          "review_period_end_at": "2026-01-31T23:59:59Z",
          "is_assessment": 0,
          "assessment_title": null,
          "assessment_ratio": null,
          "learning_content": [],
          "learning_index": [
            {
              "learner_id": 1,
              "course_id": 31,
              "index_id": 788,
              "index_type": "LESSON",
              "is_required": 1,
              "pass_score": null,
              "pass_progress_ratio": null,
              "pass_required_count": null,
              "assessment_score": null,
              "assessment_progress_ratio": null,
              "assessment_count": null,
              "index_order": 1,
              "learning_status": "PENDING",
              "parent_index_id": 787,
              "index_title": "기존 AI와 생성형 AI의 결정적 차이점",
              "learning_period_start_at": "2025-01-01T00:00:00Z",
              "learning_period_end_at": "2025-12-31T23:59:59Z",
              "learning_time": 0,
              "progress_ratio_target_type": null,
              "pass_process_timing_type": null,
              "review_period_end_at": "2026-01-31T23:59:59Z",
              "is_assessment": null,
              "assessment_title": null,
              "assessment_ratio": null,
              "learning_content": [
                {
                  "learner_id": 1,
                  "course_id": 31,
                  "index_id": 788,
                  "content_id": 1104,
                  "content_progress_type": "PLAY",
                  "learning_status": "PENDING",
                  "content_type": "VIDEO",
                  "content_order": null,
                  "is_required": 1,
                  "content_url": "https://vod.cdn.hunet.co.kr/eLearning/Hunet/HLSC88968/01_03.mp4",
                  "content_title": "기존 AI와 생성형 AI의 결정적 차이점",
                  "pass_score": 0,
                  "pass_progress_ratio": 80,
                  "pass_required_count": 0,
                  "learning_first_at": null,
                  "learning_last_at": null,
                  "learning_complete_at": null,
                  "learning_duration_sec": 0,
                  "learning_period_start_at": "2025-01-01T00:00:00Z",
                  "learning_period_end_at": "2025-12-31T23:59:59Z",
                  "content_group_no": 1,
                  "content_group_order": 1,
                  "content_scope_group_no": null,
                  "concurrent_group_no": null,
                  "concurrent_group_order": null,
                  "content_span_scope": null,
                  "utility_span_scope": null,
                  "access_condition": "PUBLIC",
                  "last_position": 0,
                  "max_position": 0,
                  "answer_count": null,
                  "correct_answer_count": null,
                  "is_answer_submitted": null,
                  "is_scored": null,
                  "obtained_score": null,
                  "view_count": null,
                  "offline_session_no": null,
                  "offline_schedule_no": null,
                  "offline_attendance_count": null,
                  "total_duration_sec": null,
                  "total_question_count": null,
                  "is_scoring_required": null,
                  "pass_correct_answer_count": null,
                  "total_position": null,
                  "content_width": 1920,
                  "content_height": 1080,
                  "offline_total_attendance_count": null
                }
              ],
              "learning_index": []
            }
          ]
        }
      ]
    }
  ]
};

